name: Build JoystickToMouse

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar MSVC
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest `
            -products * `
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath

          if (-not $vsPath) {
            Write-Error "No se encontró Visual Studio con herramientas C++."
            exit 1
          }

          Write-Host "Visual Studio encontrado en:"
          Write-Host $vsPath

          $vcvars = Join-Path $vsPath "VC\Auxiliary\Build\vcvars64.bat"

          if (-not (Test-Path $vcvars)) {
            Write-Error "No se encontró vcvars64.bat en $vcvars"
            exit 1
          }

          cmd /c "`"$vcvars`" && set" | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') {
              "$($matches[1])=$($matches[2])" >> $env:GITHUB_ENV
            }
          }

      - name: Compilar JoystickToMouse
        shell: cmd
        run: |
          cl /EHsc /O2 joysticktomouse.cpp /Fe:JoystickToMouse.exe user32.lib winmm.lib

      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: JoystickToMouse
          path: JoystickToMouse.exe
